# Generated by Django 4.1.7 on 2023-05-04 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Telephone', models.CharField(max_length=100)),
                ('IF', models.CharField(max_length=100)),
                ('ICE', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Agence',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('PRENOM', models.CharField(max_length=100)),
                ('CIN', models.CharField(max_length=100)),
                ('Telephone', models.CharField(max_length=100)),
                ('Adresse', models.CharField(max_length=100)),
                ('Num_couverture', models.CharField(max_length=100)),
                ('Salaire', models.FloatField()),
            ],
            options={
                'db_table': 'Employe',
            },
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Mileage', models.CharField(max_length=100)),
                ('Transmission', models.CharField(max_length=100)),
                ('Fuel', models.CharField(max_length=100)),
                ('Luggage', models.CharField(max_length=100)),
                ('Matricule', models.CharField(max_length=100)),
                ('Marque', models.CharField(max_length=100)),
                ('Modele', models.CharField(max_length=100)),
                ('Annee', models.IntegerField()),
                ('NbPlaces', models.IntegerField()),
                ('Couleur', models.CharField(max_length=100)),
                ('PrixParJour', models.FloatField()),
                ('IsAvailable', models.BooleanField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('Agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agence')),
            ],
            options={
                'db_table': 'Voiture',
            },
        ),
        migrations.CreateModel(
            name='Reservation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateRes', models.DateField()),
                ('DateDebut', models.DateField()),
                ('DateFin', models.DateField()),
                ('Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employe')),
                ('Voiture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.voiture')),
            ],
            options={
                'db_table': 'Reservation2',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=100)),
                ('dropoff_location', models.CharField(max_length=100)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('pickup_time', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.voiture')),
            ],
            options={
                'db_table': 'Reservation',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('PRENOM', models.CharField(max_length=100)),
                ('CIN', models.CharField(max_length=100)),
                ('Telephone', models.CharField(max_length=100)),
                ('Adresse', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Num_assurance', models.CharField(max_length=100)),
                ('Reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reservation')),
            ],
            options={
                'db_table': 'Client',
            },
        ),
    ]
